---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Deploy Panda Services
  hosts: base
  become: yes
  roles:
    - { role: docker, tags: docker }
    #- { role: nodejs, tags: nodejs }
    #- { role: bamboo, tags: bamboo }
    - { role: img-panda, tags: img-panda }
    - { role: smart-panda, tags: smart-panda }
